packages:
  - 'packages/core'
  - 'packages/sdk'
  - 'packages/api'
  - 'packages/frontend'
  - 'packages/sdk-demo'
  - 'packages/stats-worker'
  - 'packages/sdk-core'
  - 'packages/hop-node'
  - 'packages/hop-node-core'
  - 'packages/explorer-backend'
  - 'packages/explorer-frontend'
  - 'packages/v2-explorer-frontend'
  - 'packages/v2-explorer-backend'