name: Build and Push Docker Images
inputs:
  package-name:
    required: true

runs:
  using: composite
  steps:
    - name: Define Docker Tag
      run: |
        if [[ "${GITHUB_REF##*/}" == "develop" ]]; then
          echo "DOCKER_TAG=next" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF##*/}" == "production" ]]; then
          echo "DOCKER_TAG=latest" >> $GITHUB_ENV
        else
          echo "Unsupported branch" >&2
          exit 1
        fi

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@5
      with:
        context: .
        file: ./packages/${{ inputs.package-name }}/Dockerfile
        build-args: GIT_REV=${{ github.sha }}
        push: true
        tags: ${{ env.DOCKER_TAG }}
