name: Checks the status of the local package.json and packages
on:
  workflow_call:
    inputs:
      package-name:
        type: string
        description: Name of the package
    outputs:
      npm-version-changed:
        description: 'Returns a boolean indicating if there is an NPM version mismatch between the local package.json and the NPM registry.'
        value: ${{ jobs.check.outputs.npm-version-changed }}
      modified-packages:
        description: 'Returns a list of all packages (i.e. `packages/sdk`) that have been modified in any way.'
        value: ${{ jobs.check.outputs.modified-packages }}
      is-package-modified:
        description: 'Returns a boolean indicating if the passed-in package was changed in any way.'
        value: ${{ jobs.check.outputs.is-package-modified }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      npm-version-changed: ${{ steps.check-npm.outputs.npm-version-changed }}
      modified-packages: ${{ steps. modified-packages.outputs.all_changed_files }}
      is-package-modified: ${{ steps.did-change.outputs.is-package-modified }}
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Get local and current versions
        id: check-npm
        working-directory: ./packages/sdk
        run: |
          CURRENT_VERSION=$(npm info . --json | jq -r '."dist-tags".latest')
          LOCAL_VERSION=$(jq -r '.version' package.json)
          if [[ "$CURRENT_VERSION" != "$LOCAL_VERSION" ]]; then
            echo "npm-version-changed=true" >> $GITHUB_OUTPUT
          else
            echo "npm-version-changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Get modified packages
        id: modified-packages
        uses: tj-actions/changed-files@v44
        with:
          dir_names: 'true'
          dir_names_max_depth: 2

      - name: Check if passed in package changed
        id: did-change
        run: |
          if [[ "${{ steps.modified-packages.outputs.all_changed_files }}" == *"packages/${{ inputs.package-name }}"* ]]; then
            echo "is-package-modified=true" >> $GITHUB_OUTPUT
          else
            echo "is-package-modified=false" >> $GITHUB_OUTPUT
          fi 
