name: Publish Packages to NPM if Necessary
on:
  push:
    branches:
      - TODO
env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Debug'