name: deploy
on:
  push:
    branches:
      #- develop
      - feature/eslint-config-package

jobs:
  build:
    if: true
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Install node dependencies
        run: |
          npm install
          ## Install pnpm (required to build @eth-optimism packages)
          RUN npm install -g pnpm@latest
          RUN npm install -g only-allow@latest

      - name: Build the frontend app
        env:
          PUBLIC_URL: .
          REACT_APP_NETWORK: goerli
          REACT_APP_IPFS_BUILD: true
        run: npm run build --workspace=@hop-protocol/frontend

