name: Simple Github Action for Debugging Builds

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup workflow
        uses: ./.github/actions/setup
  build:
    if: false
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

      - name: Build the frontend app
        env:
          PUBLIC_URL: .
          REACT_APP_NETWORK: goerli
          REACT_APP_IPFS_BUILD: true
        run: NODE_OPTIONS=--openssl-legacy-provider pnpm build
