name: deploy
on:
  push:
    branches:
      - develop

jobs:
  build:
    if: false
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install node dependencies
        run: npm install --legacy-peer-deps

      - name: Build the frontend app
        env:
          PUBLIC_URL: .
          REACT_APP_NETWORK: goerli
          REACT_APP_IPFS_BUILD: true
        run: npm run build

