name: Simple Github Action for Debugging Builds
on:
  push:
    branches:
      - develop

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: Setup workflow
        uses: ./.github/actions/setup
  build:
    if: false
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Build the frontend app
        env:
          PUBLIC_URL: .
          REACT_APP_NETWORK: goerli
          REACT_APP_IPFS_BUILD: true
        run: NODE_OPTIONS=--openssl-legacy-provider pnpm build
