name: Publish Packages to Docker Hub if Necessary
on:
  push:
    branches:
      - develop
      - production
env:
  BRANCH_NAME: ${{ github.ref_name }}
  DOCKER_TAG: ${{ (github.ref_name == 'develop' && 'next') || (github.ref_name == 'production' && 'latest') }}

jobs:
  wait-for-npm-publish:
    runs-on: ubuntu-latest
    environment: ${{ env.BRANCH_NAME }}
    steps:
      - name: Wait for NPM packages to be built
        uses: lewagon/wait-on-check-action@ccfb013c15c8afb7bf2b7c028fb74dc5a068cccc
        with:
          ref: ${{ github.ref }}
          check-name: 'Publish SDK'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  publish-docker:
    needs: wait-for-npm-publish
    runs-on: ubuntu-latest
    environment: ${{ env.BRANCH_NAME }}
    stategy:
      matrix:
        package: [hop-node, v2-explorer-backend]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb

      - name: Login to Docker Hub
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Docker image
        if: env.CI == 'true'
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
        with:
          context: .
          file: ./packages/${{ matrix.package }}/Dockerfile
          push: true
          tags: hopprotocol/${{ matrix.package }}:${{ env.DOCKER_TAG }}
