name: Publish Packages to Docker Hub if Necessary
on:
  push:
    branches:
      - develop
      - production
env:
  DOCKER_TAG: ${{ (github.ref_name == 'develop' && 'unstable') || (github.ref_name == 'production' && 'latest') }}

jobs:
  check-version:
    uses: ./.github/workflows/npm-check-version.yml

  publish-docker:
    needs: check-version
    # Do not run on a push to the production branch if the version has not changed
    if: needs.check-version.outputs.changed == 'true' || env.DOCKER_TAG != 'latest'
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    strategy:
      matrix:
        package: [hop-node, v2-explorer-backend]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb

      - name: Login to Docker Hub
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Docker image
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
        with:
          file: ./packages/${{ matrix.package }}/Dockerfile
          tags: hopprotocol/${{ matrix.package }}:${{ env.DOCKER_TAG }}
          push: true
