name: Get modified packages
on:
  workflow_call:
    outputs:
      modified-packages:
        description: 'Returns all packages that havebeen changed in any way.'
        value: ${{jobs.modified-packages.outputs.modified-packages }}

jobs:
  modified-packages:
    runs-on: ubuntu-latest
    outputs:
      modified-packages: ${{ steps.modified-packages.outputs.sanitized_packages }}
    steps:
    - name: Checkout code
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

    - name: Get modified dirs
      id: modified-dirs
      uses: tj-actions/changed-files@a29e8b565651ce417abb5db7164b4a2ad8b6155c
      with:
        since_last_remote_commit: true
        dir_names: true
        dir_names_max_depth: 2
        separator: ','
        files: |
          packages/**

    - name: Get modified packages
      id: modified-packages
      run: |
        changed_packages="${{ steps.modified-dirs.outputs.all_changed_files }}"
        sanitized_packages=$(echo $changed_packages | sed 's/packages\///g' | tr ',' '\n' | sed 's/^ *//;s/ *$//' | jq -R -s -c 'split("\n")[:-1]')
        echo "sanitized_packages=$sanitized_packages" >> $GITHUB_OUTPUT