name: Publish Packages to NPM if Necessary
on:
  push:
    branches:
      - TODO

jobs:
  publish-sdk:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Check versions
        id: check-versions
        uses: ./.github/actions/check-version
        with:
          package-name: sdk

      - name: Setup workflow
        uses: ./.github/actions/setup

      - name: Install and build package
        if: steps.check-versions.outputs.package-version-changed == 'true'
        run: |
          pnpm --filter-prod sdk... install
          pnpm --filter sdk... build

      - name: Publish package
        if: steps.check-versions.outputs.package-version-changed == 'true'
        run: pnpm --filter sdk publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
