name: Checks if the local package.json version matches the npm registry version
on:
  workflow_call:
    outputs:
      changed:
        value: ${{ jobs.check-version.outputs.changed }}
        description: 'Indicates if there is a version mismatch'

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Get local and current versions
        id: check
        working-directory: ./packages/sdk
        run: |
          CURRENT_VERSION=$(npm info . --json | jq -r '."dist-tags".latest')
          LOCAL_VERSION=$(jq -r '.version' package.json)
          if [[ "$CURRENT_VERSION" != "$LOCAL_VERSION" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
