name: Publish Packages to NPM if Necessary
on:
  push:
    branches:
      - production

jobs:
  check-version:
    uses: ./.github/workflows/npm-check-version.yml

  publish-sdk:
    needs: check-version
    # Do not publish on a push to the production branch if the version has not changed
    if: needs.check-version.outputs.changed == 'true'
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Setup workflow
        uses: ./.github/actions/setup

      - name: Install and build package
        run: |
          pnpm --filter-prod sdk... install
          pnpm --filter sdk... build

      - name: Publish package
        run: pnpm --filter sdk publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
