name: Publish Packages to NPM if Necessary
on:
  push:
    branches:
      - develop
env:
  BRANCH_NAME: ${{ github.ref_name }}
  PACKAGE_NAME: sdk

# TODO: This will not work if some NPM packages in the workspace depend on others. Rethink this.
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    environment: ${{ env.BRANCH_NAME }}
    # Used for provenance
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Setup workflow
        uses: ./.github/actions/setup

      - name: Check if publish is necessary
        working-directory: packages/${{ env.PACKAGE_NAME }}
        run: |
          set -e
          CURRENT_VERSION=$(npm info . --json | jq -r '."dist-tags".latest')
          LOCAL_VERSION=$(jq -r '.version' package.json)
          echo "VERSION_MISMATCH=false" >> $GITHUB_ENV
          if [ "$CURRENT_VERSION" != "$LOCAL_VERSION" ]; then
            echo "VERSION_MISMATCH=true" >> $GITHUB_ENV
          fi

      - name: Install and build package
        if: env.VERSION_MISMATCH == 'true'
        run: |
          pnpm --filter-prod ${{ env.PACKAGE_NAME }}... install
          pnpm --filter ${{ env.PACKAGE_NAME }}... build

      - name: Publish package
        if: env.CI == 'true' && env.VERSION_MISMATCH == 'true'
        run: pnpm --filter ${{ env.PACKAGE_NAME }} publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
