name: Publish Packages to NPM
on:
  push:
    branches:
      - develop
    paths:
      - 'packages/sdk/**'

jobs:
  publish-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Setup workflow
        uses: ./.github/actions/setup

      - name: Check Package Updates
        id: check-package-updates
        uses: ./.github/actions/check-package-updates
        with:
          package-name: sdk

      - name: Set update flag
        if: steps.check-versions.outputs.npm-version-changed == 'true'
        run: echo "SHOULD_CONTINUE=true" >> $GITHUB_ENV
  
      - name: Install and build package
        if: env.SHOULD_CONTINUE == 'true'
        run: |
          pnpm --filter-prod sdk... install
          pnpm --filter sdk... build

      - name: Publish package
        if: env.SHOULD_CONTINUE == 'true'
        run: pnpm --filter sdk publish --publish-branch production --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
