name: Publish NPM Core Package If Necessary
on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish-core:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: 20.10.0
          registry-url: https://registry.npmjs.org

      - name: Check if publish is necessary
        id: check_version
        working-directory: packages/core
        run: |
          CURRENT_VERSION=$(npm info . --json | jq -r '."dist-tags".latest')
          LOCAL_VERSION=$(jq -r '.version' package.json)
          if [ "$CURRENT_VERSION" != "$LOCAL_VERSION" ]; then
            echo "VERSION_MISMATCH=true" >> $GITHUB_ENV
          fi

      - name: Install global dependencies
        if: env.VERSION_MISMATCH == 'true'
        working-directory: .
        run: npm install -g pnpm@latest only-allow@latest

      - name: Install local dependencies
        if: env.VERSION_MISMATCH == 'true'
        working-directory: .
        run: pnpm install

      - name: Build packages
        if: env.VERSION_MISMATCH == 'true'
        working-directory: .
        run: pnpm build

      - name: Publish package
        if: env.VERSION_MISMATCH == 'true'
        working-directory: packages/core
        run: pnpm --filter @hop-protocol/core publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
