name: Publish NPM Core Package If Necessary
on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Check version and publish if necessary
        id: check_version_publish
        run: |
          (cd ./packages/core && diff <(npx npm info . --json | jq '."dist-tags".latest') <(cat package.json | jq '.version') || (npm install -g only-allow@latest pnpm@latest && (cd ../../ && npm install) && npm publish))
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
