name: Publish Docker Image if Necessary
on:
  push:
    branches:
      - develop
      - production

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup workflow
        uses: ./.github/actions/setup

  publish-docker:
    needs: setup
    runs-on: ubuntu-latest
    environment: production
    permissions:
      packages: write
      contents: read
      attestations: write
    strategy:
      matrix:
        package: [hop-node, v2-explorer-backend]
    steps:
      - name: Define Docker Tag
        run: |
          set -e
          if [[ "${GITHUB_REF##*/}" == "develop" ]]; then
            echo "DOCKER_TAG=next" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "production" ]]; then
            echo "DOCKER_TAG=latest" >> $GITHUB_ENV
          else
            echo "Unsupported branch" >&2
            exit 1
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish Docker image
        uses: docker/build-push-action@5
        with:
          context: .
          file: ./packages/${{ matrix.package }}/Dockerfile
          build-args: GIT_REV=${{ github.sha }}
          push: true
          tags: ${{ env.DOCKER_TAG }}
