name: Publish Packages to NPM and Docker Hub if Necessary
on:
  push:
    branches:
      - develop
      - production
env:
  BRANCH_NAME: ${{ github.ref_name }}

# TODO: This will not work if some NPM packages in the workspace depend on others. Rethink this.
# TODO: This will publish to Docekr Hub on every push to develop or production. Rethink this.

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Setup workflow
        uses: ./.github/actions/setup

  publish-npm:
    needs: setup
    runs-on: ubuntu-latest
    environment: ${{ env.BRANCH_NAME }}
    # Used for provenance
    permissions:
      id-token: write
    strategy:
      matrix:
        package: [sdk]
    steps:
      - name: Check if publish is necessary
        working-directory: packages/${{ matrix.package }}
        run: |
          set -e
          CURRENT_VERSION=$(npm info . --json | jq -r '."dist-tags".latest')
          LOCAL_VERSION=$(jq -r '.version' package.json)
          echo "VERSION_MISMATCH=false" >> $GITHUB_ENV
          if [ "$CURRENT_VERSION" != "$LOCAL_VERSION" ]; then
            echo "VERSION_MISMATCH=true" >> $GITHUB_ENV
          fi

      - name: Install and build package
        if: env.VERSION_MISMATCH == 'true'
        run: |
          pnpm --filter-prod ${{ matrix.package }}... install
          pnpm --filter ${{ matrix.package }}... build

      - name: Publish package
        if: env.VERSION_MISMATCH == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: pnpm --filter ${{ matrix.package }} publish --provenance --access public

  publish-docker:
    needs: publish-npm
    runs-on: ubuntu-latest
    environment: ${{ env.BRANCH_NAME }}
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        package: [hop-node, v2-explorer-backend]
    steps:
      - name: Define Docker Tag
        run: |
          set -e
          if [[ "$BRANCH_NAME" == "develop" ]]; then
            echo "DOCKER_TAG=next" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "production" ]]; then
            echo "DOCKER_TAG=latest" >> $GITHUB_ENV
          else
            echo "Unsupported branch" >&2
            exit 1
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb

      - name: Publish Docker image
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
        with:
          context: .
          file: ./packages/${{ matrix.package }}/Dockerfile
          build-args: GIT_REV=${{ github.sha }}
          push: true
          tags: ${{ env.DOCKER_TAG }}
