name: Publish NPM Packages if Necessary
on:
  push:
    branches:
      - develop
      - production

# TODO: This will not work if some packages depend on others. Rethink this.
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup workflow
        uses: ./.github/actions/setup

  publish-npm:
    strategy:
      matrix:
        package: [sdk]
    needs: setup
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 🔍 Check if publish is necessary
        id: check_version
        working-directory: packages/${{ matrix.package }}
        run: |
          set -e
          CURRENT_VERSION=$(npm info . --json | jq -r '."dist-tags".latest')
          LOCAL_VERSION=$(jq -r '.version' package.json)
          if [ "$CURRENT_VERSION" != "$LOCAL_VERSION" ]; then
            echo "VERSION_MISMATCH=true" >> $GITHUB_ENV
          fi

      - name: 🛠️ Install and build package
        if: env.VERSION_MISMATCH == 'true'
        run: |
          pnpm --filter-prod ${{ matrix.package }}... install
          pnpm --filter ${{ matrix.package }}... build

      - name: 🚀 Publish package
        if: env.VERSION_MISMATCH == 'true'
        run: pnpm --filter ${{ matrix.package }} publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
