name: Build and Deploy Frontend UIs
on:
  push:
    branches:
      - develop
      - production
env:
  ENV_NAME: ${{ github.ref_name }}
  DNSLINK_SUBDOMAIN: ${{ (github.ref_name == 'develop' && ('_dnslink.' + github.ref_name)) || (github.ref_name == 'production' && '_dnslink.app') }}

jobs:
  wait-for-npm-publish:
    if: github.ref_name == 'production'
    runs-on: ubuntu-latest
    environment: ${{ env.ENV_NAME }}
    steps:
      - name: Wait for NPM packages to be built
        uses: lewagon/wait-on-check-action@ccfb013c15c8afb7bf2b7c028fb74dc5a068cccc
        with:
          ref: ${{ github.ref }}
          check-name: 'Publish SDK'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  deploy-ui:
    needs: wait-for-npm-publish
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.deploy.outputs.hash }}
    stategy:
      matrix:
        pacakge: [frontend]
        env-name: ['production', 'mainnet', 'sepolia']
    steps:
      - name: Deploy environment
        if: matrix.package == 'frontend'
        id: deploy
        uses: ./.github/workflows/ui-deploy-environment.yml
        with:
          ENV_NAME: ${{ matrix.env-name}}

  publish-ui:
    needs: deploy-ui
    if: github.ref_name == 'frontend'
    runs-on: ubuntu-latest
    env:
      IPFS_HASH: ${{ needs.deploy-ui.outputs.hash }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@d4be4219408b50d1bbbfd350a47cbcb126878692
        with:
          file-name: ./packages/frontend/package.json

      - name: Update CloudFlare DNS with new IPFS hash
        if: steps.check.outputs.changed
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          RECORD_DOMAIN: 'hop.exchange'
          RECORD_NAME: ${{ env.DNSLINK_SUBDOMAIN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        uses: textileio/cloudflare-update-dnslink@30414a408191218c8259e932ebdf4cbb7c652fe8
        with:
          cid: ${{ env.IPFS_HASH }}

      - name: Convert CIDv0 to CIDv1
        if: steps.check.outputs.changed
        id: convert_cidv0
        uses: uniswap/convert-cidv0-cidv1@c53a468c3602a85dd979c02ec4ddd9102849395e
        with:
          cidv0: ${{ env.IPFS_HASH }}

      - name: Create GitHub Release
        if: steps.check.outputs.changed
        env:
          CIDv0: ${{ env.IPFS_HASH }}
          CIDv1: ${{ steps.convert_cidv0.outputs.cidv1 }}
        uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87
        with:
          name: ${{ github.sha }}
          tag_name: ${{ github.sha }} }}
          body: |
            IPFS hash of the deployment:
            - CIDv0: `${{ env.CIDv0 }}`
            - CIDv1: `${{ env.CIDv1 }}`
            The latest release is always accessible via our alias to the Cloudflare IPFS gateway at [app.hop.exchange](https://app.hop.exchange).
            You can also access the Hop Interface directly from an IPFS gateway.
            **Note**: The Hop interface uses [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to remember your settings, such as slippage tolerance.
            **You should always use an IPFS gateway that enforces origin separation**, or our alias to the latest release at [app.hop.exchange](https://app.hop.exchange).
            Your Hop settings are never remembered across different URLs.
            IPFS gateways:
            - https://${{ env.CIDv1 }}.ipfs.cf-ipfs.com/
            - https://${{ env.CIDv1 }}.ipfs.dweb.link/
            - https://hop.mypinata.cloud/ipfs/${{ env.CIDv0 }}/
            - https://gateway.pinata.cloud/ipfs/${{ env.CIDv0 }}/
            - https://cloudflare-ipfs.com/ipfs/${{ env.CIDv0 }}/
            - https://gateway.ipfs.io/ipfs/${{ env.CIDv0 }}/
            - https://crustwebsites.net/ipfs/${{ env.CIDv0 }}/
            - [ipfs://${{ env.CIDv0 }}/](ipfs://${{ env.CIDv0 }}/)
            - https://hop.eth.limo/
            - https://hop.eth.link/
