name: Build and Deploy Frontend UIs
on:
  push:
    branches:
      - develop
      - production
env:
  DNSLINK_SUBDOMAIN: ${{ (github.ref_name == 'develop' && ('_dnslink.' + github.ref_name)) || (github.ref_name == 'production' && '_dnslink.app') }}

jobs:
  publish-ui:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    permissions:
      contents: write
    strategy:
      matrix:
        package: [frontend]
        env-name: ['production', 'mainnet', 'sepolia']
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Setup workflow
        uses: ./.github/actions/setup

      - name: Install package
        run: pnpm --filter-prod frontend... install

      - name: Build the app
        uses: ./.github/workflows/ui-build.yml
        with:
          env-name: ${{ matrix.env-name }}

      - name: Write commit file
        uses: DamianReeves/write-file-action@a432935930b2e351ec2d2792fc220717b656ec1c
        with:
          path: packages/frontend/dist/cachebust
          write-mode: overwrite
          contents: ${{ github.sha }}

      - name: Pin to IPFS on Pinata
        id: upload
        uses: anantaramdas/ipfs-pinata-deploy-action@9f9c3b42b5d360352c4b768d98aff1309d62faa0
        with:
          pin-name: Hop ${{ github.sha }}
          path: './packages/frontend/dist'
          pinata-api-key: ${{ secrets.IPFS_DEPLOY_PINATA__API_KEY }}
          pinata-secret-api-key: ${{ secrets.IPFS_DEPLOY_PINATA__SECRET_API_KEY }}

      - name: Check if version has been updated
        id: check
        uses: ./.github/actions/npm-check-version

      - name: Update CloudFlare DNS with new IPFS hash
        if: steps.check.outputs.changed
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          RECORD_DOMAIN: 'hop.exchange'
          RECORD_NAME: ${{ env.DNSLINK_SUBDOMAIN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        uses: textileio/cloudflare-update-dnslink@30414a408191218c8259e932ebdf4cbb7c652fe8
        with:
          cid: ${{ steps.upload.outputs.hash }}

      - name: Convert CIDv0 to CIDv1
        if: steps.check.outputs.changed
        id: convert_cidv0
        uses: uniswap/convert-cidv0-cidv1@c53a468c3602a85dd979c02ec4ddd9102849395e
        with:
          cidv0: ${{ steps.upload.outputs.hash }}}}

      - name: Create GitHub Release
        if: steps.check.outputs.changed
        env:
          CIDv0: ${{ steps.upload.outputs.hash }}}}
          CIDv1: ${{ steps.convert_cidv0.outputs.cidv1 }}
        uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87
        with:
          name: ${{ github.sha }}
          tag_name: ${{ github.sha }} }}
          body: |
            IPFS hash of the deployment:
            - CIDv0: `${{ env.CIDv0 }}`
            - CIDv1: `${{ env.CIDv1 }}`
            The latest release is always accessible via our alias to the Cloudflare IPFS gateway at [app.hop.exchange](https://app.hop.exchange).
            You can also access the Hop Interface directly from an IPFS gateway.
            **Note**: The Hop interface uses [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to remember your settings, such as slippage tolerance.
            **You should always use an IPFS gateway that enforces origin separation**, or our alias to the latest release at [app.hop.exchange](https://app.hop.exchange).
            Your Hop settings are never remembered across different URLs.
            IPFS gateways:
            - https://${{ env.CIDv1 }}.ipfs.cf-ipfs.com/
            - https://${{ env.CIDv1 }}.ipfs.dweb.link/
            - https://hop.mypinata.cloud/ipfs/${{ env.CIDv0 }}/
            - https://gateway.pinata.cloud/ipfs/${{ env.CIDv0 }}/
            - https://cloudflare-ipfs.com/ipfs/${{ env.CIDv0 }}/
            - https://gateway.ipfs.io/ipfs/${{ env.CIDv0 }}/
            - https://crustwebsites.net/ipfs/${{ env.CIDv0 }}/
            - [ipfs://${{ env.CIDv0 }}/](ipfs://${{ env.CIDv0 }}/)
            - https://hop.eth.limo/
            - https://hop.eth.link/
