name: Build and Deploy Frontend UIs
on:
  push:
    branches:
      - TODO
    # paths:
      # - 'packages/hop-node/**'

# TODO: Add sepolia
# TODO: DRY if statements

jobs:
  build-ui:
    runs-on: ubuntu-latest
    environment: ${{ matrix.env-name }}
    strategy:
      matrix:
        env-name: ['production','mainnet']
    steps:
      - name: Check versions
        id: check-versions
        uses: ./.github/actions/check-version
        with:
          package-name: frontend

      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Setup workflow
        uses: ./.github/actions/setup

      - name: Install package
        run: pnpm --filter-prod frontend... install

      - name: Build the app
        env:
          PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
          REACT_APP_NETWORK: ${{ secrets.REACT_APP_NETWORK }}
          REACT_APP_BNC_DAPP_ID: ${{ secrets.REACT_APP_BNC_DAPP_ID }}
          REACT_APP_ENABLED_CHAINS: ${{ secrets.REACT_APP_ENABLED_CHAINS }}
          REACT_APP_ENABLED_TOKENS: ${{ secrets.REACT_APP_ENABLED_TOKENS }}
          REACT_APP_DEPRECATED_TOKENS: ${{ secrets.REACT_APP_DEPRECATED_TOKENS }}
          REACT_APP_DEPRECATED_POOLS: ${{ secrets.REACT_APP_DEPRECATED_POOLS }}
          REACT_APP_DISABLED_ROUTES: ${{ secrets.REACT_APP_DISABLED_ROUTES }}
          REACT_APP_WARNING_ROUTES: ${{ secrets.REACT_APP_WARNING_ROUTES }}
          REACT_APP_DISABLE_NATIVE_ASSET_TRANSFERS: ${{ secrets.REACT_APP_DISABLE_NATIVE_ASSET_TRANSFERS }}
          REACT_APP_DISABLED_ROUTES_NO_LIQUIDITY_WARNING_MESSAGE: ${{ secrets.REACT_APP_DISABLED_ROUTES_NO_LIQUIDITY_WARNING_MESSAGE }}
          REACT_APP_SHOW_BANNER_MESSAGE: ${{ secrets.REACT_APP_SHOW_BANNER_MESSAGE }}
          REACT_APP_BLOCKLIST_ENABLED: ${{ secrets.REACT_APP_BLOCKLIST_ENABLED }}
        run: pnpm --filter frontend... build

      - name: Write commit file
        uses: DamianReeves/write-file-action@a432935930b2e351ec2d2792fc220717b656ec1c
        with:
          path: packages/frontend/dist/cachebust
          write-mode: overwrite
          contents: ${{ github.sha }}

      - name: Pin to IPFS on Pinata
        if: steps.check-versions.outputs.npm-version-changed == 'true' || matrix.env-name != 'production'
        id: upload
        uses: anantaramdas/ipfs-pinata-deploy-action@9f9c3b42b5d360352c4b768d98aff1309d62faa0
        with:
          pin-name: Hop ${{ github.sha }}
          path: './packages/frontend/dist'
          pinata-api-key: ${{ secrets.IPFS_DEPLOY_PINATA__API_KEY }}
          pinata-secret-api-key: ${{ secrets.IPFS_DEPLOY_PINATA__SECRET_API_KEY }}

      - name: Set DNSLINK_SUBDOMAIN
        id: set-dnslink-subdomain
        run: |
          if [ "${{ github.ref_name }}" == "production" ]; then
            echo "DNSLINK_SUBDOMAIN=_dnslink.app" >> $GITHUB_OUTPUT
          else
            echo "DNSLINK_SUBDOMAIN=_dnslink.${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Update CloudFlare DNS with new IPFS hash
        if: steps.check-versions.outputs.npm-version-changed == 'true' || matrix.env-name != 'production'
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          RECORD_DOMAIN: 'hop.exchange'
          RECORD_NAME: ${{ steps.set-dnslink-subdomain.outputs.DNSLINK_SUBDOMAIN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        uses: textileio/cloudflare-update-dnslink@30414a408191218c8259e932ebdf4cbb7c652fe8
        with:
          cid: ${{ steps.upload.outputs.hash }}

      - name: Convert CIDv0 to CIDv1
        if: steps.check-versions.outputs.npm-version-changed == 'true' || matrix.env-name != 'production'
        id: convert_cidv0
        uses: uniswap/convert-cidv0-cidv1@c53a468c3602a85dd979c02ec4ddd9102849395e
        with:
          cidv0: ${{ steps.upload.outputs.hash }}

      - name: Create GitHub Release
        if: steps.check-versions.outputs.npm-version-changed == 'true' || matrix.env-name != 'production'
        env:
          CIDv0: ${{ steps.upload.outputs.hash }}
          CIDv1: ${{ steps.convert_cidv0.outputs.cidv1 }}
        uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87
        with:
          name: ${{ github.sha }}
          tag_name: ${{ github.sha }}
          body: |
            IPFS hash of the deployment:
            - CIDv0: `${{ env.CIDv0 }}`
            - CIDv1: `${{ env.CIDv1 }}`
            The latest release is always accessible via our alias to the Cloudflare IPFS gateway at [app.hop.exchange](https://app.hop.exchange).
            You can also access the Hop Interface directly from an IPFS gateway.
            **Note**: The Hop interface uses [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to remember your settings, such as slippage tolerance.
            **You should always use an IPFS gateway that enforces origin separation**, or our alias to the latest release at [app.hop.exchange](https://app.hop.exchange).
            Your Hop settings are never remembered across different URLs.
            IPFS gateways:
            - https://${{ env.CIDv1 }}.ipfs.cf-ipfs.com/
            - https://${{ env.CIDv1 }}.ipfs.dweb.link/
            - https://hop.mypinata.cloud/ipfs/${{ env.CIDv0 }}/
            - https://gateway.pinata.cloud/ipfs/${{ env.CIDv0 }}/
            - https://cloudflare-ipfs.com/ipfs/${{ env.CIDv0 }}/
            - https://gateway.ipfs.io/ipfs/${{ env.CIDv0 }}/
            - https://crustwebsites.net/ipfs/${{ env.CIDv0 }}/
            - [ipfs://${{ env.CIDv0 }}/](ipfs://${{ env.CIDv0 }}/)
            - https://hop.eth.limo/
            - https://hop.eth.link/
