name: Build and Deploy Frontend UIs
on:
  push:
    branches:
      - develop
    paths:
      - 'packages/frontend/**'

jobs:
  package-updates:
    uses: ./.github/workflows/modified-packages.yml
    with:
      package-names: 'frontend'

  build-ui:
    needs: package-updates
    runs-on: ubuntu-latest
    if: ${{ fromJson(needs.package-updates.outputs.modified-packages)[0] != null }}
    environment: ${{ matrix.env-name }}
    strategy:
      matrix:
        package-name: ${{ fromJson(needs.package-updates.outputs.modified-packages) }}
        env-name:
          - production
          - mainnet
          - sepolia
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Setup workflow
        uses: ./.github/actions/setup

      - name: Check Package Updates
        id: check-package-updates
        uses: ./.github/actions/check-package-updates
        with:
          package-name: frontend

      - name: Set Update Flag
        id: set-update-flag
        run: |
          if [ "${{ matrix.env-name }}" == "production" ] && [ "${{ steps.check-package-updates.outputs.npm-package-changed }}" != "true" ]; then
            echo "SHOULD_CONTINUE=false" >> $GITHUB_OUTPUT
          else
            echo "SHOULD_CONTINUE=true" >> $GITHUB_OUTPUT
          fi

      - name: Build the app
        if: steps.set-update-flag.outputs.SHOULD_CONTINUE == 'true'
        env:
          REACT_APP_NETWORK: ${{ vars.REACT_APP_NETWORK }}
          REACT_APP_ENABLED_CHAINS: ${{ vars.REACT_APP_ENABLED_CHAINS }}
          REACT_APP_ENABLED_TOKENS: ${{ vars.REACT_APP_ENABLED_TOKENS }}
          REACT_APP_DEPRECATED_TOKENS: ${{ vars.REACT_APP_DEPRECATED_TOKENS }}
          REACT_APP_DEPRECATED_POOLS: ${{ vars.REACT_APP_DEPRECATED_POOLS }}
          REACT_APP_DISABLE_NATIVE_ASSET_TRANSFERS: ${{ vars.REACT_APP_DISABLE_NATIVE_ASSET_TRANSFERS }}
          REACT_APP_DISABLED_ROUTES_NO_LIQUIDITY_WARNING_MESSAGE: ${{ vars.REACT_APP_DISABLED_ROUTES_NO_LIQUIDITY_WARNING_MESSAGE }}
          REACT_APP_BLOCKLIST_ENABLED: ${{ vars.REACT_APP_BLOCKLIST_ENABLED }}
          REACT_APP_BNC_DAPP_ID: ${{ secrets.REACT_APP_BNC_DAPP_ID }}
        run: pnpm --filter frontend... build

      - name: Write commit file
        if: steps.set-update-flag.outputs.SHOULD_CONTINUE == 'true'
        uses: DamianReeves/write-file-action@6929a9a6d1807689191dcc8bbe62b54d70a32b42
        with:
          path: packages/frontend/dist/cachebust
          write-mode: overwrite
          contents: ${{ github.sha }}

      - name: Pin to IPFS on Pinata
        if: steps.set-update-flag.outputs.SHOULD_CONTINUE == 'true'
        id: upload
        uses: anantaramdas/ipfs-pinata-deploy-action@9f9c3b42b5d360352c4b768d98aff1309d62faa0
        with:
          pin-name: Hop ${{ github.sha }}
          path: './packages/frontend/dist'
          pinata-api-key: ${{ secrets.IPFS_DEPLOY_PINATA__API_KEY }}
          pinata-secret-api-key: ${{ secrets.IPFS_DEPLOY_PINATA__SECRET_API_KEY }}

      - name: Update CloudFlare DNS with new IPFS hash
        if: steps.set-update-flag.outputs.SHOULD_CONTINUE == 'true'
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          RECORD_DOMAIN: 'hop.exchange'
          RECORD_NAME: ${{ vars.DNSLINK_SUBDOMAIN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        uses: textileio/cloudflare-update-dnslink@30414a408191218c8259e932ebdf4cbb7c652fe8
        with:
          cid: ${{ steps.upload.outputs.hash }}

      - name: Convert CIDv0 to CIDv1
        if: steps.set-update-flag.outputs.SHOULD_CONTINUE == 'true'
        id: convert_cidv0
        uses: uniswap/convert-cidv0-cidv1@c53a468c3602a85dd979c02ec4ddd9102849395e
        with:
          cidv0: ${{ steps.upload.outputs.hash }}

      - name: Create GitHub Release
        if: steps.set-update-flag.outputs.SHOULD_CONTINUE == 'true'
        env:
          CIDv0: ${{ steps.upload.outputs.hash }}
          CIDv1: ${{ steps.convert_cidv0.outputs.cidv1 }}
        uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87
        with:
          name: ${{ github.sha }}
          tag_name: ${{ github.run_id }}
          body: |
            IPFS hash of the deployment:
            - CIDv0: `${{ env.CIDv0 }}`
            - CIDv1: `${{ env.CIDv1 }}`
            The latest release is always accessible via our alias to the Cloudflare IPFS gateway at [app.hop.exchange](https://app.hop.exchange).
            You can also access the Hop Interface directly from an IPFS gateway.
            **Note**: The Hop interface uses [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to remember your settings, such as slippage tolerance.
            **You should always use an IPFS gateway that enforces origin separation**, or our alias to the latest release at [app.hop.exchange](https://app.hop.exchange).
            Your Hop settings are never remembered across different URLs.
            IPFS gateways:
            - https://${{ env.CIDv1 }}.ipfs.cf-ipfs.com/
            - https://${{ env.CIDv1 }}.ipfs.dweb.link/
            - https://hop.mypinata.cloud/ipfs/${{ env.CIDv0 }}/
            - https://gateway.pinata.cloud/ipfs/${{ env.CIDv0 }}/
            - https://cloudflare-ipfs.com/ipfs/${{ env.CIDv0 }}/
            - https://gateway.ipfs.io/ipfs/${{ env.CIDv0 }}/
            - https://crustwebsites.net/ipfs/${{ env.CIDv0 }}/
            - [ipfs://${{ env.CIDv0 }}/](ipfs://${{ env.CIDv0 }}/)
            - https://hop.eth.limo/
            - https://hop.eth.link/
